### ISSUE TITLE
Modbus-TCP Gateway for the EMQ Broker

### ISSUE THREAD

**Issue by goodwly** [emqtt/emq-modbus#4]
hello, I don't really know the meaning of "Modbus-TCP Gateway for the EMQ Broker",Can you tell me more about it？  I'm very grateful to you

**Comment by grutabow** [comment]
This gateway accepts Modbus-TCP packets, extract its payload, and push data into EMQ broker. And mqtt client could receive Modbus payload through EMQ broker. That is to say, it is a solution to let mqtt client and modbus device to talk to each other.

This gateway could work as a modbus slave or master.

**Comment by goodwly** [comment]
Thank you for your last reply.
   I have been in touch with modbus for the first time ，so you can describe the configuration file in detail ,                expect to receive your reply again

**Comment by goodwly** [comment]
I wrote the configuration and started emq, but there was no data on the broker,so tell me Where is the problem? See, please reply，I'm very grateful to you!
